#!/bin/sh

here=$(readlink -f $(dirname $0))

while read i; do
	name=$(basename $i .git)
	if test -e $here/$name; then
		echo Updating $name...
		cd $here/$name
		git pull --recurse-submodules
	else
		cd $here
		git clone --recursive $i
	fi
	echo
done <<FIN
https://github.com/davidhalter/jedi-vim.git
https://github.com/altercation/vim-colors-solarized.git
https://github.com/nvie/vim-flake8.git
https://github.com/Lokaltog/vim-powerline.git
https://github.com/tpope/vim-fugitive.git
FIN
