#!/bin/sh

if which realpath >/dev/null; then
	here=$(dirname $(realpath -q $0))
else
	here=$(dirname $(readlink -f $0))
fi

while read i; do
	name=$(basename $i .git)
	if test -e $here/$name; then
		echo Updating $name...
		cd $here/$name
		git pull --recurse-submodules
	else
		cd $here
		git clone --recursive $i
	fi
	echo
done <<FIN
https://github.com/altercation/vim-colors-solarized.git
https://github.com/davidhalter/jedi-vim.git
https://github.com/jceb/vim-orgmode.git
https://github.com/kien/ctrlp.vim.git
https://github.com/Lokaltog/vim-powerline.git
https://github.com/natw/keyboard_cat.vim.git
https://github.com/nvie/vim-flake8.git
https://github.com/terryma/vim-multiple-cursors.git
https://github.com/tpope/vim-fugitive.git
https://github.com/vim-scripts/py-coverage.git
FIN
